receivers:
  otlp:
    endpoint: 0.0.0.0:3000

exporters:
  prometheus:
    endpoint: "0.0.0.0:4000"
    namespace: test namespace
    const_labels:
      label1: value1
      "another label": spaced value
  jaeger:
    endpoint: localhost:8080
    server_name_override: opentelemetry.io
  logging:
    loglevel: debug

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, logging]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, logging]
